### ISSUE TITLE
Ballu Heatpump don't work

### ISSUE THREAD

**Issue by Tigranik90** [ToniA/arduino-heatpumpir#101]
I opened a simple example. Connected the ESP8266 circuit. All models of air conditioners work except Ballu. When the cycle reaches "BalluHeatpumpIR", the infrared LED does not even blink.

**Comment by KameSense** [comment]
Daikin* don't work either. No blink and "Unknown or restricted command!"

**Comment by ToniA** [comment]
Ballu didn't correctly implement the HeatpumpIR interface
