### ISSUE TITLE
Panasonic hz9rke-4 heat pump

### ISSUE THREAD

**Issue by NielsLaentver** [ToniA/arduino-heatpumpir#21]
Hello.

Will this library work with the panasonic hz9rke-4 heat pump ?

Best regards
Niels

**Comment by ToniA** [comment]
So far I have seen two versions of the Panasonic protocol. Try out the one supporting DKE and newer, it probably works.

**Comment by ToniA** [comment]
So far I have seen two different versions of the Panasonic protocol, the ‘old’ up to CKP and the ‘new’, starting from DKE. Try it out and let me know, there’s a very good chance it works.
