### ISSUE TITLE
FuegoHeatpumpIR compatibility with Einhell SKA-5000 C+H Heatpump / Komeco

### ISSUE THREAD

**Issue by roquestrongo** [ToniA/arduino-heatpumpir#35]
Just want to add the information that i succesfully got a Einhell AC/Heatpump working by using the Fuego settings. 

Only thing to change was Line 65 in FuegoHeatpumpIR.cpp:

`  if ( temperatureCmd > 17 && temperatureCmd < 32)`

to

`  if ( temperatureCmd > 15 && temperatureCmd < 32)`

as the Einhells temp-range is 16°C-31°C.

Maybe this is usefull for someone looking for this AC or the identical unit sold by Komeco.

**Comment by ToniA** [comment]
Thanks, this sounds reasonable :)
