### ISSUE TITLE
Codes for Panasonic CS-KE35TKE

### ISSUE THREAD

**Issue by nardev** [ToniA/arduino-heatpumpir#36]
I do't have remote available, how can i find codes for Panasonic inverter CS-KE35TKE ?

Could it be that current Panasonic codes in this lib is appropriate for CS-KE35TKE?

**Comment by ToniA** [comment]
Just try it out, all the recent Panasonic models seem to use the same protocol. Well, there are some slight changes here and there, but they are usually about some special functionality.
