### ISSUE TITLE
Request of infos

### ISSUE THREAD

**Issue by msillano** [ToniA/arduino-heatpumpir#49]
I am very impressed with your work.
I done an application using php + mysql to manage 100+ IR protocols in IRP format (and using Arduino  for IN/OUT), for remote simulation etc.
 see https://github.com/msillano/remoteDBdiscovery.
I wold like to extend the collection: do you have some IRP for heatpumps ?
Or you can send me your protocol infos, so I can try to create the IRP formulas?

I have only  'Fujitsu_Aircon IRP', it looks so:
 '{38.4k,413}<1,-1|1,-3>(8,-4,20:8,99:8,0:8,16:8,16:8,254:8,9:8,48:8,H:8,J:8, K:8, L:8, M:8,N:8,32:8,Z:8,1,-104.3m)+ {H=16*A + wOn, J=16*C + B, K=16*E:4 + D:4, L=tOff:8, M=tOff:3:8+fOff*8+16*tOn:4, N=tOn:7:4+128*fOn,Z=256-(H+J+K+L+M+N+80)%256, A=H:4:4,wOn=H:1,B=J:4,C=J:4:4,D=K:4,E=K:4:4,tOff=L+256*M:3, tOn=M:4:4+16*N:7,fOn=N:1:7,fOff=M:1:3}' 

Best regards
Marco Sillano (marco.sillano(at)gmail.com)

**Comment by ToniA** [comment]
If you are already familiar with Arduinos, try to install the 'simple.ino' example from this repo, and see what happens. It has code examples for a number of different models.
