### ISSUE TITLE
ESPeasy crashes

### ISSUE THREAD

**Issue by hjgode** [ToniA/arduino-heatpumpir#57]
There is no issue tab for the espeasy project, so I try here:

The compile fails, as there are two classes with protected constructor used:
GreeHeatpumpIR.h
and
SamsungHeatpumpIR.h

Moved constructor to public: fixed this.

The P0115 plugin crashes looking thru the heatpumpIR array after MitsubishiMSYHeatpumpIR has been tested for the name inside the do...while loop. I use a hyundai AC.

Workaround for me was to only keep PanasonicCKPHeatpumpIR and HyundaiHeatpumpIR in the heatpumpIR array:

HeatpumpIR *heatpumpIR[] = {new PanasonicCKPHeatpumpIR(), 
/*                            new PanasonicDKEHeatpumpIR(), new PanasonicJKEHeatpumpIR(),
                            new PanasonicNKEHeatpumpIR(), new CarrierNQVHeatpumpIR(), new CarrierMCAHeatpumpIR(),
                            new MideaHeatpumpIR(), new FujitsuHeatpumpIR(),
                            new MitsubishiFDHeatpumpIR(), new MitsubishiFEHeatpumpIR(), new MitsubishiMSYHeatpumpIR(),
                            new SamsungHeatpumpIR(), new SharpHeatpumpIR(), new DaikinHeatpumpIR(),
                            new MitsubishiHeavyZJHeatpumpIR(), new MitsubishiHeavyZMHeatpumpIR(),
*/                            new HyundaiHeatpumpIR(), 
 /*                           new HisenseHeatpumpIR(), new GreeHeatpumpIR(),
                            new FuegoHeatpumpIR(), new ToshibaHeatpumpIR(),
*/                            NULL};

I had to change the platformio.ini to be able to upload a working flash image.

With Arduino 1.8.9 I had to go back to ESP8266 2.4.0-rc2 and use nodemcu v1.0 to be able to compile successfully.

It took me three days to get all this outdated stuff working.

Anyway, the code made my days. I am using the HyundaiHeatpumpIR with a HomeLiving SAC 12010QC, equal to Alaska SAC12010QC. I found the compatibilty using the AirConditionerTest.

Well done with some pitfalls for newbies

**Comment by ToniA** [comment]
OK, take a look at my ESP Easy fork: https://github.com/ToniA/ESPEasy
